### ISSUE TITLE
《Siamese Natural Language Tracker: Tracking by Natural Language Descriptions with Siamese Trackers》复现问题

### ISSUE THREAD

**Issue by Neo233333** [laisimiao/cs231n-Spring2019-assignment#7]
你好，我看到你之前在研究《Siamese Natural Language Tracker: Tracking by Natural Language Descriptions with Siamese Trackers》这篇文章的代码，请问你成功复现出来了了吗？方便留个邮箱或者其他的联系方式交流下吗？

**Comment by laisimiao** [comment]
你好，我没有复现，只是看了一下测试代码，就搞别的去了，感觉他开源的还是不太够

**Comment by Neo233333** [comment]
噢，确实开源的不太够，模型和数据集的标注都没给，谢谢了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "laisimiao/cs231n-Spring2019-assignment"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月27日(星期三) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [laisimiao/cs231n-Spring2019-assignment] 《Siamese Natural Language Tracker: Tracking by Natural Language Descriptions with Siamese Trackers》复现问题 (Issue #7)





 
你好，我没有复现，只是看了一下测试代码，就搞别的去了，感觉他开源的还是不太够
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
